######################################################################
# Automatically generated by qmake (2.01a) Tue Mar 24 20:54:04 2009
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += config_zoomer.h MainWindow.h PixmapWidget.h qimage_manip.h
SOURCES += config_zoomer.cpp main.cpp MainWindow.cpp PixmapWidget.cpp
